### ISSUE TITLE
Added Shooting Mechanics for Spacecraft

### ISSUE THREAD

**Issue by Buddhad** [Buddhad/StarlightRunaway#9]

**Comment by NessaRNG** [comment]
i already did it sir, mind to check my pull request?

**Comment by Buddhad** [comment]
Thanks for you contribution!! but if you can Just share screen shot or gifs that its works!! @NessaRNG and try to add it in scene and check it working or not cuz i see some of them you added not working properly. so carefull do that.

**Comment by Buddhad** [comment]
If you can share that i will merge as soon as possible!! @NessaRNG
